### ISSUE TITLE
Support for multiple versions

### ISSUE THREAD

**Issue by hekike** [delvedor/find-my-way#39] opened 2017-11-07 10:04 UTC
Have you ever considered to add version support to `find-my-way`?
If I understand correctly it could be a new child node in a Radix Tree below the path node.

Something like this:

```js
router.on('GET', '/', '1.2.3', (req, res, params) => {
  res.end('{"message":"hello world 1"}')
})
router.on('GET', '/', '2.0.0', (req, res, params) => {
  res.end('{"message":"hello world 2"}')
})

request({
  method: 'GET',
  uri: '/',
  headers: { 'accept-version': '~1.2'  }
}) => 'hello world 2'

request({
  method: 'GET',
  uri: '/',
  headers: { 'accept-version': '~3.1'  }
}) => 400, ~2.1 is not supported by GET /
```

Lookup could happen by `Accept-Version` header with finding the biggest version that satisfies via `semver`.

**Comment by mcollina** [comment] 2017-11-08 11:49
This would be a good addition, as long as it does not slow things down. My worry is if we need to add a check for this in all the other nodes,

**Comment by delvedor** [comment] 2017-11-08 14:51
I'll check if I can implement it without compromising the performances.
This router should be as light as possible.

**Comment by hekike** [comment] 2017-11-08 14:57
@delvedor thanks!

**Comment by i5ting** [comment] 2017-11-14 16:07
@hekike maybe use store is a good choice!

```
router.on('GET', '/example', (req, res, params, store) => {
  assert.equal(store, { message: 'hello world' })
  ....
}, { 
  versions: {
    '1.2.3': function(req, res) {},
    '1.2.4': function(req, res) {}
  } 
})
```

**Comment by delvedor** [comment] 2017-11-14 16:21
@i5ting it could be a solution, but the problem is that we should use semver, which as far as I know uses regular expressions a lot.

To lower the friction that this change will introduce we should find a way to store the different handlers in the Node and define which one use inside the `find` algorithm, based on the presence of the `Accept-Version` header.

I'm working on this.

**Comment by delvedor** [comment] 2017-11-14 16:53
@hekike I'm wondering if we want to support a semver range in the declaration:
```js
router.on('GET', '/', '>=2.5.0', (req, res, params) => {
  res.end('{"message":"hello world 1"}')
})
```

**Comment by hekike** [comment] 2017-11-14 22:14
How about that routes have a fix version number like `1.0.0`, `1.1.0` and 2.0.0` and the `accept-version` header should tell it's expectations with `semver` ranges like `~1.0.0`, `^1.0.0` or `2.x` and router should find the best fitting version.

For example:

```js
router.on('GET', '/', 1.1.0', (req, res, params) => {
  res.end('"hello world 1.1.0')
})
router.on('GET', '/', '1.2.0', (req, res, params) => {
  res.end('hello world 1.2.0')
})

// 'accept-version': '^1.1.0' => 'hello world 1.2.0'
```

**Comment by delvedor** [comment] 2017-11-18 17:12
I thought about this and there is not an easy way to insert it without compromising the performances and the structure of the tree.
Because you should add a check every time you call `lookup` for the presence of the header and change the Node structure to handle multiple pair method:path with different versions.

The easiest solution without compromising the performances is to build a wrapper around `find-my-way`, like the following:
https://gist.github.com/delvedor/0cbb4aadefc5384ae17ad8305ea567e8

If you have some better solution, please ake a proposal! :)

**Comment by hekike** [comment] 2017-11-18 17:23
Okay, thanks for putting effort into it.
Your solution looks good, with a couple of versions it should be performant as well.

For now, we will handle route versioning with a middleware that sits after `find-my-way`:
https://github.com/restify/node-restify/blob/9a017158ca077b0ab4a4e0cad0e4709a79e2b74d/lib/plugins/conditionalHandler.js#L38

**Comment by mcollina** [comment] 2018-02-28 11:40
Awesome. Closing this then.

**Closed by mcollina** 2018-02-28 11:40 UTC

**Comment by delvedor** [comment] 2018-06-08 15:45
https://github.com/delvedor/find-my-way/pull/79
