### ISSUE TITLE
support for multiple params

### ISSUE THREAD

**Issue by mcollina** [delvedor/find-my-way#17] opened 2017-07-13 11:00 UTC
I think the current problem for #15 is not about regexps. It's about multiple params in the same part:

```
/hello/:my-:world.html
```

Currently, find-my-way only supports one parameter within two `/`.

**Comment by delvedor** [comment] 2017-07-16 18:13
Our first goal is to not compromise the performances, and a feature like this would do it.

The only solution I see now is to discover if we are adding a *multiple parametric route* during the insertion and create a new kind of node, in this way at runtime we will not spent time trying splitting the parameter on `'-'`, but we'll do that only if we are in a *multiple parametric* node. In this way the performance impact will be low, just another `if` check.

The problem is how design the node object, since we are working with a radix tree, having multiple parameter could be hard to store and handle.

**Comment by brunoscopelliti** [comment] 2017-09-23 09:40
Hi @delvedor ,
I've tried to add support for multi parametric routes. I've followed your suggestion, and created a new node type for this kind of route.
Any feedback is appreciated.

**Comment by delvedor** [comment] 2017-09-27 17:11
Closed in #27

**Closed by delvedor** 2017-09-27 17:11 UTC
Labels: feature
