### ISSUE TITLE
Using regex to capture the URL parameters

### ISSUE THREAD

**Issue by gajus** [delvedor/find-my-way#15] opened 2017-07-07 10:52 UTC
The following route definition works in Express.js, but does not work in Fastify/ find-my-way
, `/cinema-logos/:cinemaId(\\d+)-:cinemaName.svg`.

In Fastify, it produces `params: { 'cinemaId(\d+)-:cinemaName.svg': '1000146-vue.svg' },`, whereas I expect to get `cinemaId` and `cinemaName` as separate parameters.

`:cinemaId-:cinemaName` is not working either, because the matching expression appears to be greedy: `'cinemaId-:cinemaName.svg': '1000146-vue.svg'`.

**Comment by gajus** [comment] 2017-07-07 10:55
Looks like only one parameter can be used per "directory", https://github.com/delvedor/find-my-way/blob/41bdc50f823c47a6c716b746c7cf9dd0bb723ca7/index.js#L53-L54

This is very limiting ..

**Comment by mcollina** [comment] 2017-07-07 11:08
Thanks for reporting this! We should definitely have a look on how to best handle support for multiple dynamic parts of the URL.

Do you see a quick fix for this?

**Comment by gajus** [comment] 2017-07-07 11:12
Not unless you allow to use a regex in the URIs.

**Comment by mcollina** [comment] 2017-07-07 11:14
@gajus I do not think that will work, given how this library works.
However, `:cinemaId-:cinemaName` might do?

**Comment by gajus** [comment] 2017-07-07 11:16
You could just allow regex as the route definition. That would be an acceptable option, and it would be straightforward to implement, e.g.

```js
app.get('/cinema-logos/:cinemaId(\\d+)-:cinemaName([a-z0-9-]+).svg', ...

```

would become

```js
app.get(/\/cinema-logos\/(?<cinemaId>\d+)-(?<cinemaName>[a-z0-9-]+).svg/, ...

```

Named capture groups are stage 3, https://github.com/tc39/proposal-regexp-named-groups.

**Comment by gajus** [comment] 2017-07-07 11:17
> @gajus I do not think that will work, given how this library works.
> However, :cinemaId-:cinemaName might do?

You'd still need to allow to define regex for the parameter matching groups. That wouldn't be neither more performant or more convenient.

**Comment by mcollina** [comment] 2017-07-07 11:18
Given how it is implemented, I do not think this library could easily support regexps. Feel free to try a PR if you think it's easy or feasible.

**Comment by gajus** [comment] 2017-07-07 11:21
I've gone back to using Express.js as this issue is a deal-breaker and I doubt you are going to have fix soon. Raised an issue for reference.

**Comment by mcollina** [comment] 2017-07-07 11:24
Thanks for reporting!

**Comment by delvedor** [comment] 2017-07-07 11:47
We could support regex, but we should add a new kind of node to avoid performances regression, since regular expressions are terribly slow. I'll work on this.

> Named capture groups are stage 3, https://github.com/tc39/proposal-regexp-named-groups.

One of our focus is compatibility, so use new features is not a viable option.

Thanks for reporting.

**Comment by gajus** [comment] 2017-07-07 11:59
> We could support regex, but we should add a new kind of node to avoid performances regression, since regular expressions are terribly slow. I'll work on this.

I thought about this at first too. However, I don't see how you are going to prioritize the routes using a fallback routing mechanism.

**Comment by delvedor** [comment] 2017-07-13 10:20
Partially closed in #16, parameters group will arrive in a future pr, currently is not high priority.

**Comment by gajus** [comment] 2017-07-13 10:40
> Partially closed in #16, parameters group will arrive in a future pr, currently is not high priority.

The current addition does not add anything to find-my-way that was not already supported by using Fastify with parameter validation.

**Comment by delvedor** [comment] 2017-07-13 10:45
Correct, as I told you [here](https://github.com/fastify/fastify/issues/122#issuecomment-313694575).

If you have some suggestions on how implement grouping parameters I'll be happy to hear them! :)

**Comment by delvedor** [comment] 2017-07-16 17:24
Since this issue has been addressed I think we can close it, and leave open just #17.

**Closed by delvedor** 2017-07-16 17:24 UTC
